### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by dcstang** [dcstang/dcstang.github.io#1]
- [ ] Write up header, footer and body
- [ ] Link up all previous projects
- [ ] Layout: intro and blog
